### ISSUE TITLE
verb tags metabug

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-kaz-kir#1]
Some morphological tags associated with verbs need to be dealt with:
- [ ] `<gna_impf>` → `<gna_perf>` (most cases)
- [x] `<prc_fplan>` → `<prc_fplan>`
- [ ] `<gpr_fut><subst>` → `<ger_pres>`
